typography_spectrum: 0.26071277423761785
color:
  saturation: 0.8818917
  brandStrength: 0
  rhythmicContrast: 0.6571582
  brandColors:
    - '#F2FAFC'
    - '#A2BD30'
    - '#ABD8FA'
    - '#1F65D0'
    - '#07392A'
  lightness: 0.8116232
layout_spectrum: 0.21299630706198514
name: deBewusteSamenleving.nl
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Swinkels
