layout_spectrum: 0.7334557
typography_spectrum: 0.1620735
color:
  saturation: 0.8818917
  lightness: 0.8116232
  brandStrength: 0
  brandColors:
    - '#F2FAFC'
    - '#A2BD30'
    - '#ABD8FA'
    - '#1F65D0'
    - '#07392A'
  rhythmicContrast: 0.6571582
name: SWINKELS.ES
